[package]
name = "lassy"
version = "0.1.0"
authors = ["rn"]

[dependencies]
# rustc-llvm-proxy = "0.1"
# llvm-sys = { version = "60.2", features = ["no-llvm-linking"] }
combine = "3.6.3"
num = "0.2.0"
unicode_categories = "0.1.1"