[package]
name = "diyusi"
version = "0.1.0"
authors = ["Ner"]

[dependencies]
combine = "3.6.3"
num = "0.2.0"
unicode_categories = "0.1.1"
env_logger = "0.6.0"
log = "0.4.6"

serde = { version = "1.0.88" , features = ["rc"] }
serde_derive = "1.0.88"
rmp-serde = "0.13.7"